apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: task-manager

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: tejasweetaskmanageracr2026.azurecr.io/task-manager-backend:v2

          ports:
            - containerPort: 5000

          env:
            - name: DB_HOST
              value: postgres

            - name: DB_PORT
              value: "5432"

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_NAME

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20