name: Task Manager CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  ACR_LOGIN_SERVER: tejasweetaskmanageracr2026.azurecr.io
  ACR_NAME: tejasweetaskmanageracr2026
  RESOURCE_GROUP: task-manager-devops-rg
  AKS_CLUSTER: task-manager-aks
  NAMESPACE: task-manager

jobs:

  # -----------------------------
  # CI: Build and Push Images
  # -----------------------------
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: 32f4a325-43b7-4855-ac96-40e604edfdd1
          tenant-id: 2eb66361-ee69-4224-82b1-f5f9821d811c
          subscription-id: 98aab639-1e25-4dc3-804f-34c11d8ccf76

      - name: Login to Azure Container Registry
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build backend Docker image
        run: |
          docker build \
            -t ${{ env.ACR_LOGIN_SERVER }}/task-manager-backend:${{ github.sha }} \
            ./backend

      - name: Build frontend Docker image
        run: |
          docker build \
            --build-arg VITE_API_URL=/api/tasks \
            -t ${{ env.ACR_LOGIN_SERVER }}/task-manager-frontend:${{ github.sha }} \
            ./frontend

      - name: Push backend Docker image
        run: |
          docker push ${{ env.ACR_LOGIN_SERVER }}/task-manager-backend:${{ github.sha }}

      - name: Push frontend Docker image
        run: |
          docker push ${{ env.ACR_LOGIN_SERVER }}/task-manager-frontend:${{ github.sha }}


  # -----------------------------
  # CD: Deploy to AKS
  # -----------------------------
  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: 32f4a325-43b7-4855-ac96-40e604edfdd1
          tenant-id: 2eb66361-ee69-4224-82b1-f5f9821d811c
          subscription-id: 98aab639-1e25-4dc3-804f-34c11d8ccf76

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.AKS_CLUSTER }} \
            --overwrite-existing

      - name: Verify AKS connection
        run: |
          kubectl get nodes

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/namespace.yaml
          kubectl apply -f kubernetes/postgres-pvc.yaml
          kubectl apply -f kubernetes/postgres-deployment.yaml
          kubectl apply -f kubernetes/postgres-service.yaml
          kubectl apply -f kubernetes/backend-deployment.yaml
          kubectl apply -f kubernetes/backend-service.yaml
          kubectl apply -f kubernetes/frontend-deployment.yaml
          kubectl apply -f kubernetes/frontend-service.yaml

      - name: Update backend image
        run: |
          kubectl set image deployment/backend \
            backend=${{ env.ACR_LOGIN_SERVER }}/task-manager-backend:${{ github.sha }} \
            --namespace ${{ env.NAMESPACE }}

      - name: Update frontend image
        run: |
          kubectl set image deployment/frontend \
            frontend=${{ env.ACR_LOGIN_SERVER }}/task-manager-frontend:${{ github.sha }} \
            --namespace ${{ env.NAMESPACE }}

      - name: Wait for backend rollout
        run: |
          kubectl rollout status deployment/backend \
            --namespace ${{ env.NAMESPACE }} \
            --timeout=180s

      - name: Wait for frontend rollout
        run: |
          kubectl rollout status deployment/frontend \
            --namespace ${{ env.NAMESPACE }} \
            --timeout=180s

      - name: Verify application pods
        run: |
          kubectl get pods \
            --namespace ${{ env.NAMESPACE }}

      - name: Verify services
        run: |
          kubectl get services \
            --namespace ${{ env.NAMESPACE }}