name: Task Manager CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  ACR_LOGIN_SERVER: tejasweetaskmanageracr2026.azurecr.io
  ACR_NAME: tejasweetaskmanageracr2026

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: 32f4a325-43b7-4855-ac96-40e604edfdd1
          tenant-id: 2eb66361-ee69-4224-82b1-f5f9821d811c
          subscription-id: 98aab639-1e25-4dc3-804f-34c11d8ccf76

      - name: Login to Azure Container Registry
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build backend Docker image
        run: |
          docker build \
            -t ${{ env.ACR_LOGIN_SERVER }}/task-manager-backend:${{ github.sha }} \
            ./backend

      - name: Build frontend Docker image
        run: |
          docker build \
            --build-arg VITE_API_URL=/api/tasks \
            -t ${{ env.ACR_LOGIN_SERVER }}/task-manager-frontend:${{ github.sha }} \
            ./frontend

      - name: Push backend Docker image
        run: |
          docker push ${{ env.ACR_LOGIN_SERVER }}/task-manager-backend:${{ github.sha }}

      - name: Push frontend Docker image
        run: |
          docker push ${{ env.ACR_LOGIN_SERVER }}/task-manager-frontend:${{ github.sha }}